'use client';

import { jsPDF } from 'jspdf';
import { Download } from 'lucide-react';
import styles from './SoulBookGenerator.module.css';

interface SoulBookProps {
    name?: string;
    hebrewDate?: string;
    tikkun?: string;
}

export default function SoulBookGenerator({
    name = "Seeker",
    hebrewDate = "Unknown Date",
    tikkun = "Your path is yet to be revealed."
}: SoulBookProps) {

    const generatePDF = () => {
        const doc = new jsPDF();

        // Set background (black unlikely to print well, so utilizing white with gold text concept)
        // Actually, for a "Book", a parchment style or clean white is best.
        // Let's go for a clean mystical look.

        // Title
        doc.setFont("times", "bold");
        doc.setFontSize(30);
        doc.setTextColor(212, 175, 55); // Gold
        doc.text("The Book of Your Soul", 105, 40, { align: "center" });

        // Subtitle
        doc.setFont("helvetica", "normal");
        doc.setFontSize(14);
        doc.setTextColor(0, 0, 0); // Black
        doc.text(`Prepared for: ${name}`, 105, 55, { align: "center" });

        // Divider
        doc.setLineWidth(0.5);
        doc.setDrawColor(212, 175, 55);
        doc.line(40, 60, 170, 60);

        // Section 1: The Time //
        doc.setFont("times", "bold");
        doc.setFontSize(18);
        doc.setTextColor(10, 25, 47); // Deep Blue
        doc.text("I. The Time of Entry", 20, 80);

        doc.setFont("helvetica", "normal");
        doc.setFontSize(12);
        doc.setTextColor(60, 60, 60);
        doc.text(`Your soul descended into this world on the Hebrew date of:`, 20, 90);

        doc.setFont("times", "bolditalic");
        doc.setFontSize(16);
        doc.setTextColor(212, 175, 55);
        doc.text(hebrewDate, 20, 100);

        // Section 2: The Correction //
        doc.setFont("times", "bold");
        doc.setFontSize(18);
        doc.setTextColor(10, 25, 47);
        doc.text("II. The Tikkun (Correction)", 20, 120);

        doc.setFont("helvetica", "normal");
        doc.setFontSize(12);
        doc.setTextColor(60, 60, 60);

        const splitTikkun = doc.splitTextToSize(tikkun, 170);
        doc.text(splitTikkun, 20, 130);

        // Footer
        doc.setFontSize(10);
        doc.setTextColor(150, 150, 150);
        doc.text("Generated by Kabbalah Portal", 105, 280, { align: "center" });

        doc.save(`${name.replace(/\s+/g, '_')}_Soul_Book.pdf`);
    };

    return (
        <button onClick={generatePDF} className={styles.downloadBtn}>
            <Download size={20} />
            <span>Download the Book of Your Soul</span>
        </button>
    );
}
